# Generated by Django 5.0.2 on 2024-04-01 02:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authorization', '0001_initial'),
        ('subscription', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountsubscription',
            name='base_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='base_subscription_set', to='subscription.basesubscriptionplans'),
        ),
        migrations.AddField(
            model_name='accountsubscription',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_subscriptions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='address',
            name='account',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='my_addresses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mentorbasesubscriptionplans',
            name='mentor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_plans', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mentorsubscriptions',
            name='farmer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscribed_mentors_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mentorsubscriptions',
            name='mentor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_farmers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mentorsubscriptions',
            name='mentor_base_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentor_subscription_set', to='authorization.mentorbasesubscriptionplans'),
        ),
        migrations.AddField(
            model_name='otp',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='otp_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='planfeaturesthrough',
            name='base_subscription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authorization.accountsubscription'),
        ),
        migrations.AddField(
            model_name='planfeaturesthrough',
            name='subscription_features',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subscription.essentialfeatures'),
        ),
        migrations.AddField(
            model_name='accountsubscription',
            name='plan_features',
            field=models.ManyToManyField(through='authorization.PlanFeaturesThrough', to='subscription.essentialfeatures'),
        ),
    ]
