# Generated by Django 5.0.2 on 2024-03-12 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0003_rename_is_farm_staff_accounts_is_farmer_staff_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='accounts',
            managers=[
            ],
        ),
        migrations.AddField(
            model_name='accounts',
            name='is_admin',
            field=models.BooleanField(default=True),
        ),
    ]
