# Generated by Django 5.0.2 on 2024-03-12 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0004_alter_accounts_managers_accounts_is_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='accounts',
            name='is_admin',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AlterField(
            model_name='accounts',
            name='user_type',
            field=models.CharField(blank=True, choices=[('FARMER', 'FARMER'), ('MENTOR', 'MENTOR')], default='FARMER', max_length=50, null=True),
        ),
    ]
