# Generated by Django 5.0.2 on 2024-03-12 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0005_alter_accounts_is_active_alter_accounts_is_admin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='is_farmer_staff',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
