# Generated by Django 5.0.2 on 2024-03-15 18:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0006_alter_accounts_is_farmer_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='account',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='my_addresses', to=settings.AUTH_USER_MODEL),
        ),
    ]
