# Generated by Django 5.0.2 on 2024-03-26 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0007_alter_address_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='remark',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
