# Generated by Django 5.0.2 on 2024-03-26 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0008_address_remark'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='remark',
        ),
        migrations.AddField(
            model_name='address',
            name='stripe_cus_id',
            field=models.CharField(blank=True, null=True),
        ),
    ]
