# Generated by Django 5.0.2 on 2024-03-31 09:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0009_remove_address_remark_address_stripe_cus_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planfeaturesthrough',
            name='feature_type',
            field=models.CharField(choices=[('BASE_SUBSCRIPTION_FEATURE', 'BASE_SUBSCRIPTION_FEATURE'), ('ADD_ON_FEATURE', 'ADD_ON_FEATURE')], default='BASE_SUBSCRIPTION_FEATURE'),
        ),
        migrations.CreateModel(
            name='MentorBaseSubscriptionPlans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodicity', models.CharField(max_length=50)),
                ('amount', models.FloatField()),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_plans', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='mentorsubscriptions',
            name='mentor_base_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentor_subscription_set', to='authorization.mentorbasesubscriptionplans'),
        ),
    ]
