# Generated by Django 5.0.2 on 2024-04-21 11:12

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountSubscription',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('valied_till', models.DateField()),
                ('base_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='base_subscription_set', to='subscription.basesubscriptionplans')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MentorBaseSubscriptionPlans',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('periodicity', models.CharField(max_length=50)),
                ('amount', models.FloatField()),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_plans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='paymenttransactions',
            name='mentor_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='forme_transactions', to='subscription.mentorbasesubscriptionplans'),
        ),
        migrations.CreateModel(
            name='MentorSubscriptions',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('valied_till', models.DateField()),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscribed_mentors_set', to=settings.AUTH_USER_MODEL)),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_farmers', to=settings.AUTH_USER_MODEL)),
                ('mentor_base_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentor_subscription_set', to='subscription.mentorbasesubscriptionplans')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PlanFeaturesThrough',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('feature_type', models.CharField(choices=[('BASE_SUBSCRIPTION_FEATURE', 'BASE_SUBSCRIPTION_FEATURE'), ('ADD_ON_FEATURE', 'ADD_ON_FEATURE')], default='BASE_SUBSCRIPTION_FEATURE')),
                ('base_subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subscription.accountsubscription')),
                ('subscription_features', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subscription.essentialfeatures')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='accountsubscription',
            name='plan_features',
            field=models.ManyToManyField(through='subscription.PlanFeaturesThrough', to='subscription.essentialfeatures'),
        ),
    ]
