# Generated by Django 5.0.2 on 2024-03-31 09:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0010_alter_planfeaturesthrough_feature_type_and_more'),
        ('subscription', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymenttransactions',
            name='mentor',
        ),
        migrations.AddField(
            model_name='paymenttransactions',
            name='mentor_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='forme_transactions', to='authorization.mentorbasesubscriptionplans'),
        ),
        migrations.AddField(
            model_name='paymenttransactions',
            name='stripe_session_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
