# Generated by Django 5.0.2 on 2024-04-23 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0002_accountsubscription_mentorbasesubscriptionplans_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymenttransactions',
            name='invoice_pdf',
            field=models.FileField(blank=True, null=True, upload_to='invoices'),
        ),
        migrations.AlterField(
            model_name='paymenttransactions',
            name='stripe_session_id',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
