# Generated by Django 5.0.2 on 2024-04-27 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0003_alter_paymenttransactions_invoice_pdf_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='essentialfeatures',
            name='periodicity',
            field=models.CharField(blank=True, choices=[('DAILY', 'DAILY'), ('MONTHLY', 'MONTHLY'), ('YEARLY', 'YEARLY')], default='MONTHLY', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='basesubscriptionplans',
            name='plan_validity',
            field=models.IntegerField(default=30),
        ),
    ]
