# Generated by Django 5.0.2 on 2024-04-27 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0004_essentialfeatures_periodicity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentorbasesubscriptionplans',
            name='periodicity',
            field=models.CharField(choices=[('WEEKLY', 'WEEKLY'), ('MONTHLY', 'MONTHLY'), ('YEARLY', 'YEARLY')], max_length=50),
        ),
    ]
